[theme]
# Primary accent color for interactive elements.
primaryColor = "#ff1493"  

# Background color for the main content area.
backgroundColor = "#2c003e"  

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#4b0066" 

# Color used for almost all text.
textColor = "#ffccff" 

[client]
toolbarMode = "minimal"
